### ISSUE TITLE
 Generating with reference images, are those id same

### ISSUE THREAD

**Issue by ericyq** [HaiyuWu/Vec2Face#4]
>>>python image_generation_with_reference.py \
--image_file "path/of/the/image/file or folder" \
--model_weights weights/vec2face_generator.pth \
--batch_size 5 \
--example 10 \
--name images-of-references

**Comment by HaiyuWu** [comment]
This code provide a image-wise way to generate x examples for each reference image you provided. For example, if you have 
5 images and ```--example 10```, this code will generate 10 images for each of 5 images. These 10 images are supposed to be the same identity as the reference image.

**Comment by ericyq** [comment]
thanks!
sometimes, not like the same person.

**Comment by HaiyuWu** [comment]
If the images are not cropped and aligned, the results will be bad.

**Comment by taotaoorange** [comment]
> If the images are not cropped and aligned, the results will be bad.

Why does it have to be aligned?

**Comment by HaiyuWu** [comment]
> > If the images are not cropped and aligned, the results will be bad.
> 
> Why does it have to be aligned?

To generate samples with the same identity as the reference image, the first step is using a face recognition model to extract the feature of the reference image. If it is not cropped and aligned, the feature quality will be bad as the FR model was only trained with cropped and aligned images. Bad feature quality won't contain detailed information of face, so the generated images will be bad.

The other face generation model integrated a face detector in their pipeline, so they do not require the pre-processed images. I did not do it because for low resolution images (112x112), face detector will give you a "face not detected error". Moreover, this model is not for fancy face editing, so it is not necessary to integrate it into the pipeline.
